<?php

/**
 * Implements hook_menu()
 */
function error_log_jira_menu() {
  // The paths given here need to match the ones in foobar.routing.yml exactly.
  $items['/error_log_jira'] = array(
    'title' => 'Error log jira settings',
    'route_name' => 'error_log_jira.list',
  );
  return $items;
}

/**
 * Implements hook_permission()
 */
function error_log_jira_permission() {
  return array(
    'administer error log jira' => array(
      'title' => t('Manage error log jira form submissions'),),
  );
}

